#ifndef CONSTANTS_H
#define CONSTANTS_H

const int SCREEN_WIDTH = 720, SCREEN_HEIGHT = 480;
const int BALLS_COUNT = 15, BALL_RADIUS = 20;
const int BALLS_SPEED = 1;
const int BALLS_VECT_MAX = 3;

const int INNER = 150;

const int WALL_TOP_X1 = INNER - 50, WALL_TOP_Y1 = INNER, WALL_TOP_X2 = SCREEN_WIDTH - INNER, WALL_TOP_Y2 = INNER;
const int WALL_LEFT_X1 = INNER - 50, WALL_LEFT_Y1 = INNER, WALL_LEFT_X2 = INNER, WALL_LEFT_Y2 = SCREEN_HEIGHT - INNER;
const int WALL_RIGHT_X1 = SCREEN_WIDTH - INNER + 100, WALL_RIGHT_Y1 = INNER, WALL_RIGHT_X2 = SCREEN_WIDTH - INNER, WALL_RIGHT_Y2 = SCREEN_HEIGHT - INNER;
const int WALL_BOTTOM_X1 = INNER + 100, WALL_BOTTOM_Y1 = SCREEN_HEIGHT - INNER, WALL_BOTTOM_X2 = SCREEN_WIDTH - INNER, WALL_BOTTOM_Y2 = SCREEN_HEIGHT - INNER;

#endif // CONSTANTS_H