#ifndef CONSTANTS_H
#define CONSTANTS_H

const int SCREEN_WIDTH = 720, SCREEN_HEIGHT = 480;
const int BALLS_COUNT = 10, BALL_RADIUS = 20;
const float BALLS_SPEED = 1;
const int BALLS_VX_MIN = -3, BALLS_VY_MIN = -3, BALLS_VX_MAX = 3, BALLS_VY_MAX = 3;

#endif // CONSTANTS_H